---
# Déploie le filtre DNS AdGuard Home
- name: Créer le dossier AdGuard
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/lab-dacs/adguard
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"

- name: Copier les fichiers d'AdGuard
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../adguard/docker-compose.yml"
    dest: /home/{{ ansible_user }}/lab-dacs/adguard/docker-compose.yml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"

- name: Démarrer AdGuard avec Docker Compose
  community.docker.docker_compose_v2:
    project_src: /home/{{ ansible_user }}/lab-dacs/adguard
    state: present
  become: true
