---
- name: Redémarrer CrowdSec
  ansible.builtin.systemd:
    name: crowdsec
    state: restarted

- name: Redémarrer le bouncer CrowdSec
  ansible.builtin.systemd:
    name: crowdsec-firewall-bouncer
    state: restarted
