---
services:
  adguard:
    image: adguard/adguardhome:v0.107.53
    container_name: adguard
    # Nom du serveur hôte, fourni par Ansible dans .env (NODE_HOSTNAME)
    hostname: ${NODE_HOSTNAME:-adguard}
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "127.0.0.1:3001:3000/tcp"
      - "127.0.0.1:8090:80/tcp"
    volumes:
      - ./work:/opt/adguardhome/work
      - ./conf:/opt/adguardhome/conf
    restart: unless-stopped
